chore: upgrade installation steps
ministero-salute/it-dgc-verificac19-sdk-android pull request #40
Opened 2021-10-19 13:31 UTC by astagi

2021-10-19 14:15 UTC, Light2288 requested changes
In the second point of step 2, remove reference to attached file

2021-10-19 15:18 UTC, astagi commented
Done @Light2288

2021-10-19 15:49 UTC, Light2288 approved these changes

2021-10-19 15:51 UTC, merged

2021-10-20 15:09 UTC, frankdsarn commented
ciao a tutti,
ho seguito i suggerimenti ma rimango fermo sempre allo stesso punto, chi ha qualche suggerimento ? ho aggiunto maggiori dettagli su questo issue:
https://github.com/ministero-salute/it-dgc-verificac19-sdk-android/issues/23#issuecomment-947759451
grazie mille