Feature: change recovery rules
ministero-salute/it-dgc-verificac19-sdk-android pull request #41
Opened 2021-10-19 14:56 UTC by Light2288

changed validity rules for recovery statements

2021-10-19 15:25 UTC, astagi requested changes
@Light2288 is it possible to add a test for these changes?

2021-10-20 14:55 UTC, astagi commented
@Light2288 @nicola-95 @simonedev97 I see you added tests great work! can I start review it again?

2021-10-20 15:09 UTC, Light2288 commented
@astagi as we were working on recovery tests, we are also completing the ones for tests and vaccines; I'll let you know when tests are completed and request again your review, thank you
@simonedev97 @nicola-95

2021-10-20 18:30 UTC, astagi approved these changes

2021-10-20 18:31 UTC, merged